// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfd1ZWDYOyDnddULT1ObQrOGO3tSFNHnM',
    appId: '1:430097022944:web:3521341c50f42455dfb585',
    messagingSenderId: '430097022944',
    projectId: 'flutter-firebase-dc111',
    authDomain: 'flutter-firebase-dc111.firebaseapp.com',
    storageBucket: 'flutter-firebase-dc111.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfsQGIv_mxNK90qgKHknQUGj_xJqS-5o0',
    appId: '1:430097022944:android:4a28dccfff5ffc62dfb585',
    messagingSenderId: '430097022944',
    projectId: 'flutter-firebase-dc111',
    storageBucket: 'flutter-firebase-dc111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbB5I9d0A06M3vEMzyF_DW4iEhRPjGZk4',
    appId: '1:430097022944:ios:16565e3a9e1cce21dfb585',
    messagingSenderId: '430097022944',
    projectId: 'flutter-firebase-dc111',
    storageBucket: 'flutter-firebase-dc111.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbB5I9d0A06M3vEMzyF_DW4iEhRPjGZk4',
    appId: '1:430097022944:ios:2cd1325624db4c4bdfb585',
    messagingSenderId: '430097022944',
    projectId: 'flutter-firebase-dc111',
    storageBucket: 'flutter-firebase-dc111.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
